### ISSUE TITLE
adjust_text doesn't appear to respect horizontal alignment

### ISSUE THREAD

**Issue by adrn** [Phlya/adjustText#92]
Example [taken from the documentation](https://adjusttext.readthedocs.io/en/latest/Examples.html#A-very-simple-example-also-shown-in-the-wiki-to-simply-introduce-the-call-signature-of-adjust_text), adding `ha='center'` to `plt.text()` calls:
```python
np.random.seed(0)
x, y = np.random.random((2,30))
fig, ax = plt.subplots()
plt.plot(x, y, 'bo')
texts = [plt.text(x[i], y[i], 'Text%s' %i, ha='center') for i in range(len(x))]
```
![image](https://user-images.githubusercontent.com/583379/80118614-a5966500-8556-11ea-9633-737d157fe510.png)
Text is horizontally centered properly.

Now run `adjust_text`:
```python
fig, ax = plt.subplots()
plt.plot(x, y, 'bo')
texts = [plt.text(x[i], y[i], 'Text%s' %i, ha='center') for i in range(len(x))]
adjust_text(texts)
```
![image](https://user-images.githubusercontent.com/583379/80118744-d7a7c700-8556-11ea-92cb-0358f19c925c.png)

**Comment by Phlya** [comment]
Please try using the `ha` argument of `adjust_text` and set `autoalign` to `False` or `y`.

**Comment by Phlya** [comment]
Try setting the alignment when creating the text objects?

**Comment by McLawrence** [comment]
This does not work for me: 

```
np.random.seed(0)
x, y = np.random.random((2,30))
fig, ax = plt.subplots()
plt.plot(x, y, 'bo')

texts = [plt.text(x[i]+0.01, y[i], 'Text%s' %i, ha='left', va="center") for i in range(len(x))]
```
![random_points](https://github.com/Phlya/adjustText/assets/25885486/2ec18f6e-2dae-44e4-9c08-ab6f2a424c7f)

but with `adjust_text`: 

adding `adjust_text(texts, arrowprops=dict(arrowstyle="->", color='black', lw=0.5))`:

![random_points_adjusted](https://github.com/Phlya/adjustText/assets/25885486/85a7e3ec-87df-4b40-b983-647bdf66fe80)

Many of the texts like `Text22` or `Text4` don't overlap with each other. Is there a way to keep them at their position, with the left aligned to the dot? Preferably, this should always be the case if no arrow is used.

**Comment by Phlya** [comment]
OK, what exactly are you trying to achieve? If you want the texts to always be to the right of the points, you need to use the 'only_move='x+y' argument. 
![image](https://github.com/Phlya/adjustText/assets/2895034/f5a1583e-8dfc-434c-ae43-393a97128ea4)

'ha' just affects the actual alignment of the matplotlib Text object relative to its reference coordinates, and since the text locations are adjusted, it doesn't really matter.

**Comment by McLawrence** [comment]
Thanks! That already solves some of my problems. I tried to solve it with `only_move` but did not know about the + notation. 

However, using `adjust_text(texts, arrowprops=dict(arrowstyle="->", color='black', lw=0.5), only_move='x+')` with the same code as above moves texts slightly to the left. 
![random_points_adjusted](https://github.com/Phlya/adjustText/assets/25885486/6e5929f2-8560-493c-90a0-8f6539faae1a)

See how `Text8` in the top right corner has moved to the right. I thought it might not have actually moved to the right, but the aligment changed from `left` to `center`. 

What I would ideally like to achieve is that labels that don't overlap just stay exactly where they are. I could manually do that by only passing texts that actually overlap, but that would be a lot of work for the amounts of points and charts that I plan to do. So texts that overlap can even move to the left if they move far and have an arrow, but if possible, I would like text to stay where they start.

**Comment by Phlya** [comment]
That's a good idea for a feature, actually.

At the moment it is complicated, trying to restrict things globally also makes the adjustment of overlapping texts significantly worse.

Other things to try that can help:
`explode_radius=0`

First step is "explosion" of texts away from all other points/objects in their vicinity, even if they are not overlapping, this ensures they move in the "right" direction, away from dense areas.

`expand=(1, 1)`
Normally text bounding boxes are slightly expanded to promote small padding between texts and points/other objects to avoid. This should reduce "unnecessary" movement.

I am not sure why, but even with these settings the texts actually move a little bit...
![image](https://github.com/Phlya/adjustText/assets/2895034/209db0ec-52d8-4d48-83a1-e2a6d5ef4bb5)

**Comment by Phlya** [comment]
```python
adjust_text(texts, arrowprops=dict(arrowstyle="->", color='black', lw=0.5), only_move={'text':'x+y',
                                                                                       'static':'x+',
                                                                                       'explode':'x+',
                                                                                       'pull':''},
            explode_radius=0,
            expand=(1, 1))
```
Try something like this?
![image](https://github.com/Phlya/adjustText/assets/2895034/79cefa4e-9b27-49db-978f-b538341affb0)

**Comment by Phlya** [comment]
Ah here something: not sure why, but the movement of non-overlapping texts can be prevented if instead of using the (default) `avoid_self=True` you use `avoid_self=False, x=x, y=y,`, in combination with expand=(0.99, 0.99). E.g.
```python
adjust_text(texts, arrowprops=dict(arrowstyle="->", color='black', lw=0.5), only_move={'text':'x+y',
                                                                                       'static':'x+y',
                                                                                       'explode':'',
                                                                                       'pull':''},
            avoid_self=False,
            x=x, y=y,
            explode_radius=0,
            force_pull=(0, 0),
            expand=(0.99, 0.99))
```
gives
![image](https://github.com/Phlya/adjustText/assets/2895034/52dc10e1-c800-47ac-a561-550d26a82ec3)

**Comment by McLawrence** [comment]
Thanks for the experimentation! I will try these ideas for my specific use case.

**Comment by Phlya** [comment]
Also try using the latest release now! I fixed some issues, I think it works better in general.

**Comment by marcus-r-kelly** [comment]
The underlying issue is still very present; even with `autoalign=False` the text is realigned to have center horizontal alignment, and the bounding boxes are calculated based on that alignment.

**Comment by Phlya** [comment]
> The underlying issue is still very present; even with `autoalign=False` the text is realigned to have center horizontal alignment, and the bounding boxes are calculated based on that alignment.

There is no autoalign argument in the latest version.

But indeed the alignment is always set to "center" after new coordinates are found, for consistency. Why is that an issue?
